# Base configuration for the project
defaults:
  - search: "default_search"
  - policy: "rl_policy"
  - env: "cifar10_env"

search:
  num_episodes: 1000
  num_workers: 8
  use_gpu: true

policy:
  learning_rate: 1e-4
  gamma: 0.99
  clip_param: 0.2

env:
  dataset: "cifar10"
  max_epochs: 50